# Generated by Django 2.2 on 2019-05-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektwahl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='mitglieder',
            field=models.IntegerField(default=0),
        ),
    ]
