# Generated by Django 2.2 on 2019-05-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektwahl', '0004_schueler_klasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schueler',
            name='projekt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektwahl.Projekt'),
        ),
    ]
