# Generated by Django 2.2 on 2019-05-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektwahl', '0005_auto_20190505_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schueler',
            name='projekt',
        ),
        migrations.AddField(
            model_name='schueler',
            name='drittWahl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drittWahl', to='projektwahl.Projekt'),
        ),
        migrations.AddField(
            model_name='schueler',
            name='erstWahl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erstWahl', to='projektwahl.Projekt'),
        ),
        migrations.AddField(
            model_name='schueler',
            name='zweitWahl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zweitWahl', to='projektwahl.Projekt'),
        ),
    ]
